import { createTRPCClient, httpBatchLink } from '@trpc/client'
import type { AppRouter } from '../generated/appRouter'

// The NestJS gateway. Same-origin in dev and prod: in dev the gateway proxies non-API routes to Vite and
// serves /trpc itself; in prod it serves this bundle and /trpc on one port. So the client uses relative
// URLs — no VITE_API_URL, no CORS. The AppRouter type is generated by the gateway's typegen adapter on boot
// (apps/web/src/generated/appRouter.d.ts, committed + regenerated). No subscriptions today → a single
// batched HTTP link.
export const trpc = createTRPCClient<AppRouter>({
  links: [httpBatchLink({ url: '/trpc' })],
})
