import { createTRPCClient, httpBatchLink } from '@trpc/client'
import type { AppRouter } from '../generated/appRouter'
import { notifyAuthExpired } from './auth'

// The NestJS gateway. Same-origin in dev and prod: in dev the gateway proxies non-API routes to Vite and
// serves /trpc itself; in prod it serves this bundle and /trpc on one port. So the client uses relative
// URLs — no VITE_API_URL, no CORS. The AppRouter type is generated by the gateway's typegen adapter on boot
// (apps/web/src/generated/appRouter.d.ts, committed + regenerated). No subscriptions today → a single
// batched HTTP link.
//
// Auth rides on the HttpOnly session cookie that the login exchange set, so nothing here attaches a
// credential — same-origin requests carry it for free. What this DOES do is notice when the gateway stops
// accepting it: the fetch wrapper is the one choke point every tRPC call passes through, so a 401 anywhere
// becomes a single "session expired" signal instead of an error each call site would have to handle.
export const trpc = createTRPCClient<AppRouter>({
  links: [
    httpBatchLink({
      url: '/trpc',
      fetch: async (input, init) => {
        const res = await fetch(input, init)
        if (res.status === 401) notifyAuthExpired()
        return res
      },
    }),
  ],
})
